tom_insl1: ./censor_win -dataset ../1/split_sensorInsulinaa -id tom_insl1 -port 1234 -x 0 -y 1 -z 1 -interval 10 -duration 20
tom_pressure1: ./censor_win -dataset ../1/split_sensorBloodPressureaa -id tom_pressure1 -port 1235 -x 0 -y 3 -z 2 -interval 15 -duration 50
tom_temp1: ./censor_win -dataset ../1/split_sensorTempratureaa -id tom_temp1 -port 1236 -x 4 -y 4 -z 4 -interval 5 -duration 10
