cccc1: ./main -dataset 1.txt -id sensor1 -port 1234 -x 1 -y 1 -z 1 -interval 20 -duration 5
cccc2: ./main -dataset 2.txt -id sensor2 -port 1235 -x 2 -y 2 -z 2 -interval 10 -duration 100
cccc3: ./main -dataset 3.txt -id sensor3 -port 1236 -x 4 -y 4 -z 4 -interval 5 -duration 10
